### ISSUE TITLE
Use GNUInstallDirs

### ISSUE THREAD

**Issue by rossburton** [nfs-ganesha/ntirpc#150]
Instead of a few ntirpc-specific options which are not flexible to set install paths, please consider using GNUInstallDirs.

https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

This lets the packager pass all the usual variables in one shot to put the files in the right place.  In particular, hardcoding the library install path to $prefix/lib or $prefix/lib64 isn't useful if the user is cross compiling or needs some form of multilib.

**Comment by dang** [comment]
We haven't been supporting cross compiling, mostly because no one needed it, and none of us developers are currently set up to test it.
That said, patches are welcome, as long the current use cases (normal install, install into a prefix, and installation as as submodule of Ganesha) continue to work.

**Comment by ffilz** [comment]
I'm going to close this, I don't see us working on this any time soon or anyone contributing a patch.
