### ISSUE TITLE
Why use xprt->xp_fd_send rather than xprt->xp_fd ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/ntirpc#297]
When svc_rqst_evchan_write, we use xprt->xp_fd_send = dup(xprt->xp_fd), and then use xp_fd_send in epoll_ctl. But why use xp_fd_send, rather than xp_fd ? 
Looking forward to you reply.

**Comment by xiaods** [comment]
> use xp_fd_send in epoll_ctl

please clear your question, don't know your mean abt which line: " use xp_fd_send in epoll_ctl"

**Comment by liyinshubyte** [comment]
@xiaods sorry, it's my fault,  code at [svc_rqst.c:858](https://github.com/nfs-ganesha/ntirpc/blob/5bfd6cb1e0a1e69336a3e258f249f2c11b495121/src/svc_rqst.c#L858) use xp_fd_send to epoll_ctl, but at [svc_rqst.c: 818](https://github.com/nfs-ganesha/ntirpc/blob/5bfd6cb1e0a1e69336a3e258f249f2c11b495121/src/svc_rqst.c#L818) use xp_fd to epoll_ctl. So curious about what's difference of xp_fd_send and xp_fd to epoll_ctl.

```
			/* add to epoll vector */
			code = epoll_ctl(sr_rec->ev_u.epoll.epoll_fd,
					 EPOLL_CTL_ADD, rec->xprt.xp_fd_send,
					 ev);
```

**Comment by dang** [comment]
xp_fd is used to handle incoming data to ntirpc.  The fairness strategy that ntripc uses to make sure that all clients get an equal chance is based on the fairness of epoll, so we only use incoming epoll events on that FD.

However, sometimes we need to be able to block on write to an FD, for example when the client did a large READ operation.  In order to not mess up the fairness for incoming clients, we duplicate the FD into xp_send_fd for those cases, and use epoll with only outgoing events on that FD to track the sent data.

**Comment by liyinshubyte** [comment]
Got it. Thanks a lot.
