### ISSUE TITLE
Needless fork?

### ISSUE THREAD

**Issue by onlyjob** [nfs-ganesha/ntirpc#36]
Please document differences from the [original project](https://github.com/linuxbox2/ntirpc).

Why this fork exists? Wouldn't it be better to cooperate around one authoritative repository?

Needless [forking](https://en.wikipedia.org/wiki/Fork_%28software_development%29) is [harmful](http://blog.bacula.org/why-forking-is-bad/) as forks cause fragmentation and confusion.

See also https://github.com/linuxbox2/ntirpc/issues/9

**Comment by mattbenjamin** [comment]
Hi Again,

----- Original Message -----
> From: "Dmitry Smirnov" <notifications@github.com>
> To: "nfs-ganesha/ntirpc" <ntirpc@noreply.github.com>
> Cc: "Subscribed" <subscribed@noreply.github.com>
> Sent: Tuesday, January 17, 2017 4:47:12 PM
> Subject: [nfs-ganesha/ntirpc] Needless fork? (#36)
> 
> Please document differences from the [original
> project](https://github.com/linuxbox2/ntirpc).

The main ones are:

1. nfs-ganesha/ntirpc.git maintains authoritative copies of all interesting ntirpc branches and ensures they are up-to-date
2. linuxbox2/ntirpc.git does not maintain copies of interesting branches or ensure any branches are up-to-date
3. linuxbox2/ntirpc.git contains work-in-progress branches by a few authors, mainly me--it is a bit of a mess, since it's main purpose is to be a staging area for work awaiting upstream review

> 
> Why this fork exists? Wouldn't it be better to cooperate around one
> authoritative repository?

As we've explained, yes, of course it's better to share one authoritative repository.  Our authoritative repository is nfs-ganesha/ntirpc.git.  The reason for using that repository is so that ntirpc would be owned and maintained by the upstream maintainers of nfs-ganesha, which everyone in the project prefers.

> 
> Needless
> [forking](https://en.wikipedia.org/wiki/Fork_%28software_development%29) is
> [harmful](http://blog.bacula.org/why-forking-is-bad/) as forks cause
> fragmentation and confusion.

You're looking at an old repository that we, the upstream project, moved from one place to another, and assuming it's a fork.  There is no fork.

> 
> See also https://github.com/linuxbox2/ntirpc/issues/9

Sorry about that, as Daniel noted, we didn't realize we had issue tracking in the wrong places.  This has since been fixed.

HTH,

Matt

> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nfs-ganesha/ntirpc/issues/36

-- 
Matt Benjamin
Red Hat, Inc.
315 West Huron Street, Suite 140A
Ann Arbor, Michigan 48103

http://www.redhat.com/en/technologies/storage

tel.  734-821-5101
fax.  734-769-8938
cel.  734-216-5309

**Comment by ffilz** [comment]
As release manager (aka maintainer) of nfs-ganesha, I will add my voice that for the Ganesha project, the nfs-ganesha/ntirpc repo is considered the authoritative repo. 

 

For historical reasons, the ntirpc project was started under the linuxbox2 repo and thus forked into nfs-ganesha, but for the past several years, the Ganesha community has been treating the nfs-ganesha repo as the authoritative one, with linuxbox2 just being a contributors repo. If I recall my history, the linuxbox2 repo pre-dates the nfs-ganesha repo, when Philippe Deniel was sole maintainer of Ganesha and the primary Ganesha repo was his personal Github phdeniel.

 

If we could reverse the forking without losing issue tracker and pull request history, it could make the current state more clear to folks, on the other hand, the forking preserves the history of the project.

 

The key point though is that the nfs-ganesha Github organization represents the community surrounding Ganesha and ntirpc.

 

I hope that adds some clarity.

 

Of course being open source, folks are welcome to fork their own work off of any repo they desire so long as all licensing requirements are followed… I do hope that folks however will respect the existing communities and fork from the community accepted authoritative repo.

 

Frank
